### ISSUE TITLE
JSON Web Token sucks?

### ISSUE THREAD

**Issue by Nothing-Works** [fChristenson/My-life-as-a-programmer#12]
as this article mentioned http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/

what's your thought about this? and if this is true, what we do for API auth? use some Auth services?

**Comment by fChristenson** [comment]
The author is correct in most of this, personally I would say that you can use a JWT for internal validation if you need a extra layer of security but you could ofc just encrypt a custom header value and use that instead.

Usually API authentication is done by providing the client with a API key that is included in a request usually by having the key either created by the API provider and given to the client or by using OAuth and have the client get approval from their user to extract information on their behalf from the provider.

If you are making your own API you would simply provide a auth endpoint to your client if you have many and they would provide you with credentials and the response will be a key they then use to make requests to the API, if you only have a few known clients you can simply hardcode the key and give it to them.

If you need to have a stateful application using sessions works just fine imo.
