### ISSUE TITLE
Turorial link for 'full stack Java roadmap' does not work

### ISSUE THREAD

**Issue by sebinbenjamin** [fChristenson/My-life-as-a-programmer#13]
The link for **full stack Java roadmap** at https://github.com/fChristenson/My-life-as-a-programmer/blob/master/tutorials.md#tutorials pointing to https://www.youtube.com/edit?o=U&video_id=2ZRSDWrH--Y does not seem to work.

![image](https://user-images.githubusercontent.com/4099066/62438613-e4388500-b765-11e9-9307-28a9c379f975.png)

**Comment by fChristenson** [comment]
Fixed, thanks for letting me know.

The video won't be released for some time but if you want to check out the repo here it is:
https://github.com/fChristenson/java-roadmap
