### ISSUE TITLE
Make a video about the social aspects of programming

### ISSUE THREAD

**Issue by Edza** [fChristenson/My-life-as-a-programmer#3]
In this video at this timestamp:
https://youtu.be/5ozRR8Trf8Q?t=322

You talk about introvert programmers having it harder because programming has now become more social. I am extremely interested in this topic as personality psychology enthusiast. What did you mean by this? Are you sure?

You could make a video. Thanks

**Comment by fChristenson** [comment]
Hi Edza!

I have put together a video on this, thanks for the suggestion!

**Comment by Edza** [comment]
It's not out yet, right?

**Comment by fChristenson** [comment]
No it's in the queue, I am going to make a few videos on the topic as it is a bit wider than what I can fit in one video.
