### ISSUE TITLE
Some broken links

### ISSUE THREAD

**Issue by Nothing-Works** [fChristenson/My-life-as-a-programmer#5]
Hi Fredrik Christenson

I think, 
some links are broken such as 
### How do I get better with React?

https://youtu.be/Z0IFrptov0c

**Comment by fChristenson** [comment]
Hi m8!

No these are just videos that aren't released yet, I haven't thought out a good way to segment released videos from scheduled ones that doesn't produce a lot of extra work for me.

Have a great day!
