### ISSUE TITLE
New project options for react.

### ISSUE THREAD

**Issue by Nothing-Works** [fChristenson/My-life-as-a-programmer#7]
Hi Fredrik Christenson,

I have a question about how are you going to start a new SPA project, for example, let's say if you were to start a brand new SPA project (maybe in VUE or React). 

Which approach would prefer (Using React as an example): 

1. Set up all from scratch and config everything all by yourself in order to suit you best.
2. Go with the official CLI (create-react-app)
3. Some frameworks built on top of the library like Next.js or Gatsby
4. Something else I have not mentioned yet.

Can you please tell me your opinion of these options (pros and cons)? or it depends on the level of the developer?

Many thanks in advance.

**Comment by fChristenson** [comment]
Hi m8!

My rule of thumb is to always do it from scratch unless I have to use a generator tool.

Wrapper tools are a crutch that brings a lot of danger with it both for your project and for your own learning so I never use them.

Once you know your tools by heart the generator projects are almost a joke as they save you a couple of minutes at best but the damage they can do to your learning is massive if you use them too soon.

You will not get stronger by using an elevator but using the stairs will.

Have a great day m8!
